export enum PopularCities {
  NewYork = 'New York',
  LosAngeles = 'Los Angeles',
  Chicago = 'Chicago',
  Houston = 'Houston',
  Phoenix = 'Phoenix',
  Philadelphia = 'Philadelphia',
  SanAntonio = 'San Antonio',
  SanDiego = 'San Diego',
  Dallas = 'Dallas',
  SanJose = 'San Jose',
  Austin = 'Austin',
  Jacksonville = 'Jacksonville',
  SanFrancisco = 'San Francisco',
  Columbus = 'Columbus',
  Indianapolis = 'Indianapolis',
  FortWorth = 'Fort Worth',
  Charlotte = 'Charlotte',
  Seattle = 'Seattle',
  Denver = 'Denver',
  ElPaso = 'El Paso',
  Detroit = 'Detroit',
}
